import type { Moment } from '../types/runbook.types'

export const RUNBOOK_MOMENTS: Moment[] = [
  // ── ESCOLA SABATINA ───────────────────────────────────────
  {
    id: 'pre-escola',
    label: 'Pré Escola Sabatina',
    category: 'escola',
    sceneHint: 'screenShare',
    hardwareInstructions: ['Liga o projetor', 'Verifica microfones'],
    softwareActions: [{ type: 'set-scene', scene: 'screenShare' }],
    status: 'pending',
  },
  {
    id: 'abertura-escola',
    label: 'Abertura',
    category: 'escola',
    sceneHint: 'camera',
    softwareActions: [{ type: 'set-scene', scene: 'camera' }],
    status: 'pending',
  },
  {
    id: 'hino-1',
    label: 'Hino',
    category: 'escola',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-hymn' },
    ],
    status: 'pending',
  },
  {
    id: 'boletim-missionario',
    label: 'Boletim Missionário',
    category: 'escola',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-file', hint: 'Seleciona o vídeo do Boletim Missionário' },
    ],
    status: 'pending',
  },
  {
    id: 'recapitulacao',
    label: 'Recapitulação Lição',
    category: 'escola',
    sceneHint: 'camera',
    softwareActions: [{ type: 'set-scene', scene: 'camera' }],
    status: 'pending',
  },
  {
    id: 'hino-2',
    label: 'Hino',
    category: 'escola',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-hymn' },
    ],
    status: 'pending',
  },
  {
    id: 'fecho-escola',
    label: 'Fecho Escola Sabatina',
    category: 'escola',
    sceneHint: 'camera',
    softwareActions: [{ type: 'set-scene', scene: 'camera' }],
    status: 'pending',
  },

  // ── CULTO ─────────────────────────────────────────────────
  {
    id: 'musica-louvor',
    label: 'Música de Louvor',
    category: 'culto',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-hymn' },
    ],
    status: 'pending',
  },
  {
    id: 'anuncios',
    label: 'Anúncios',
    category: 'culto',
    sceneHint: 'screenWithCam',
    hardwareInstructions: ['Liga câmara frontal se estava desligada'],
    softwareActions: [
      { type: 'set-scene', scene: 'screenWithCam' },
      { type: 'open-file', hint: 'Seleciona o PowerPoint de anúncios' },
    ],
    status: 'pending',
  },
  {
    id: 'pre-culto',
    label: 'Pré Culto',
    category: 'culto',
    sceneHint: 'screenShare',
    softwareActions: [{ type: 'set-scene', scene: 'screenShare' }],
    status: 'pending',
  },
  {
    id: 'entrada-culto',
    label: 'Entrada Culto',
    category: 'culto',
    sceneHint: 'camera',
    hardwareInstructions: ['Liga microfone do pastor'],
    softwareActions: [{ type: 'set-scene', scene: 'camera' }],
    status: 'pending',
  },
  {
    id: 'oracao-1',
    label: 'Oração',
    category: 'culto',
    sceneHint: 'camera',
    status: 'pending',
  },
  {
    id: 'hino-3',
    label: 'Hino',
    category: 'culto',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-hymn' },
    ],
    status: 'pending',
  },
  {
    id: 'oracao-joelhos',
    label: 'Oração de Joelhos',
    category: 'culto',
    sceneHint: 'camera',
    hardwareInstructions: ['Câmara pode baixar levemente para mostrar congregação'],
    status: 'pending',
  },
  {
    id: 'hino-4',
    label: 'Hino',
    category: 'culto',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-hymn' },
    ],
    status: 'pending',
  },
  {
    id: 'video-ofertas',
    label: 'Vídeo Ofertas',
    category: 'culto',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-file', hint: 'Seleciona o vídeo de Ofertas/Mordomia' },
    ],
    status: 'pending',
  },
  {
    id: 'musica-ofertas',
    label: 'Música Ofertas',
    category: 'culto',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-hymn' },
    ],
    status: 'pending',
  },
  {
    id: 'oracao-ofertas',
    label: 'Oração Ofertas',
    category: 'culto',
    sceneHint: 'camera',
    softwareActions: [{ type: 'set-scene', scene: 'camera' }],
    status: 'pending',
  },
  {
    id: 'musica-criancas',
    label: 'Música Crianças',
    category: 'culto',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-hymn' },
    ],
    status: 'pending',
  },
  {
    id: 'culto-sermao',
    label: 'Culto / Sermão',
    category: 'culto',
    sceneHint: 'camera',
    hardwareInstructions: ['Confirma microfone do pastor ativo'],
    softwareActions: [{ type: 'set-scene', scene: 'camera' }],
    status: 'pending',
  },
  {
    id: 'hino-5',
    label: 'Hino',
    category: 'culto',
    sceneHint: 'screenShare',
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'open-hymn' },
    ],
    status: 'pending',
  },
  {
    id: 'oracao-final',
    label: 'Oração Final',
    category: 'culto',
    sceneHint: 'camera',
    softwareActions: [{ type: 'set-scene', scene: 'camera' }],
    status: 'pending',
  },
  {
    id: 'saida-culto',
    label: 'Saída Culto',
    category: 'culto',
    sceneHint: 'screenShare',
    hardwareInstructions: ['Podes desligar microfone do pastor'],
    softwareActions: [
      { type: 'set-scene', scene: 'screenShare' },
      { type: 'stop-stream' },
    ],
    status: 'pending',
  },
]
